spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    hikari:
      username: root
      password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
